### PR TITLE
Add user-select CSS to #pass

### PR DESCRIPTION
**Pull request by thomasbnt**
I just simply added `user-select: all` for select all password without double click

### CODE REVIEW

**Comment by AnalogCyan** [comment]
Thank you for your contribution! This is a useful change I hadn't thought to add.
Though, if you could please update it to include all variants of `user-select` as not all browsers always respect simply `user-select`:

```css
  -webkit-user-select: all;
  -moz-user-select: all;
  -ms-user-select: all;
  user-select: all;
```

[CSS-Tricks](https://css-tricks.com/almanac/properties/u/user-select/)
[MDN Docs](https://developer.mozilla.org/en-US/docs/Web/CSS/user-select)

**Comment by thomasbnt** [comment]
> Though, if you could please update it to include all variants of user-select as not all browsers always respect simply user-select:

Oh yeep 👌

**Comment by thomasbnt** [comment]
Thanks @AnalogCyan for merged this little changement. 

I've got a question, how I can add Netlify checks for PR like this? 
image

**Comment by AnalogCyan** [comment]
> I've got a question, how I can add Netlify checks for PR like this? image

If you are deploying via Netlify as I am here, you can use the Netlify GitHub integration to automate the deploy process, run Netlify-specific checks, and automatically generate deploy previews as you see here. You can learn more on the [Netlify Docs](https://docs.netlify.com/configure-builds/repo-permissions-linking/).

**Comment by thomasbnt** [comment]
Thanks!

**Pull request merged**
