### PR TITLE
Separates out ingredients and dishes, increases number of combinations

### PR DESCRIPTION
**Pull request by brianbloom**
_(updated pull request after changes for automated linter checks)_
This makes a separate list of recipes/final dishes, and appends this after (slider-1) ingredients.
The additions to the lists increase the overall randomness from 1.7 billion combinations previously to over 1.8 billion.
Lists are sorted to allow for quick checking of included or missing terms
(I had to redo everything to fit the axios functions that got added after I had originally redone the lists.)
(There are also still PWA errors which are not addressed by this change)

### CODE REVIEW

**Comment by AnalogCyan** [comment]
What PWA errors are you seeing? Doing a quick test on my end, PWA functionality appears to be working fine and have no major issues.

Also FYI, you can add additional changes to an existing pull request, no need to close it and make a new one.

**Comment by brianbloom** [comment]
> What PWA errors are you seeing? Doing a quick test on my end, PWA functionality appears to be working fine and have no major issues.

I sometimes see this:
"Source map error: Error: request failed with status 404
Resource URL: https://cdn.jsdelivr.net/npm/@pwabuilder/pwaupdate
Source Map URL: pwa-update.js.map"

> Also FYI, you can add additional changes to an existing pull request, no need to close it and make a new one.
Sorry, I'm a bit new to Github - last platform I used (and it was long time ago) was SourceForge with CVS, so it's taking some time to get comfortable with Git.

**Comment by brianbloom** [comment]
I'm not sure why the linter is still balking at this:
**generate.js**
'i' used outside of binding context.

`for (var i = 0; i < slider.value-1; i++) {`

I guess it's either because there is a second _var i_ declared later, or maybe because i is declared but not actually used in that block?  The only change I made to that line was to add the "-1" to leave room for a recipe word.

**Comment by AnalogCyan** [comment]
> I'm not sure why the linter is still balking at this:
> **generate.js**
> 'i' used outside of binding context.
> 
> `for (var i = 0; i < slider.value-1; i++) {`

It's also complaining about this on the currently live code, so it's nothing you did. Probably is just complaining about it again since you've made an edit to that line causing it to re-evaluate it (and thus come to the same conclusion).

**Comment by AnalogCyan** [comment]
> I sometimes see this:
> "Source map error: Error: request failed with status 404
> Resource URL: https://cdn.jsdelivr.net/npm/@pwabuilder/pwaupdate
> Source Map URL: pwa-update.js.map"

This simply means it's occasionally failing to load the SourceMap for `pwa-update.js`... for whatever reason. Regardless of _why_ it's failing, it's not app-breaking and can be investigated later if it persists after merging this.

That aside, everything seems to work fine. Thanks for you contributions!

**Pull request merged**
